#!/bin/bash

# Prevents running in home directory
if test $(pwd) == $HOME ; then
  echo 'Do not run this script in root'
  exit 1;
fi

# Only run in whitelist projects
#whitelist_projects=("obsidian" "_dotfiles" "_tasks" "_utils")
#echo "${whitelist_projects[*]}"
#echo $(PWD)
#if [[ ! "${whitelist_projects[*]} " =~ " $(pwd) "]] ; then
#  echo 'Please whitelist this project to run auto-save'
#  exit 1;
#fi

# Checks if location is git initialized
if [ ! -e '.git' ] ; then
	echo 'This is not a git repository - run git init'
	exit 1;
fi

gstatus="git status --porcelain"

if [ ${#gstatus} -ne 0 ]
then
  git add --all
  git commit -m "chore(autosave): $(date +"%Y-%m-%d %H:%M:%S")"
    git pull --rebase
  git push
else
  git pull
fi

exit 0
