#!/bin/bash

if [ -r .grepignore ]; then
  while read -r line; do
    # Checking if a comment or end of line
    if [[ "$line" =~ '#' ]] || [[ "$line" =~ ^$ ]]; then
      continue
    fi

    if [[ "$line" =~ /$ ]] ; then
      EXCLUDE="$EXCLUDE --exclude-dir=\"$line\""
    else
      EXCLUDE="$EXCLUDE --exclude=\"$line\""
    fi
  done < .grepignore
fi

eval grep -r "$EXCLUDE" '"$@"' --color=always
