#!/bin/bash
# Check if in a react application

if [ $# -eq 0 ] ; then
  echo "No arguements supplied"
  exit 1;
fi

echo "Setup Path"
# ~/Users/andregomes/Documents/workspace/app
$APP_ROOT_PATH = pwd

# Prevents committing in root folder
if test $(pwd) == $HOME ; then
      echo "Do not run this script in root"
      exit 1;
fi

# Check if in a JS folder
is_application_init = false
if [ -e "package.json" ] ; then
	# Application is already create
	is_application_init = true
fi

exit 1;

function add_boilerplate_files {
    mkdir -p ./src/{components,screens,_services,_helpers,constants}
    touch ./src/{components,screens,_services,_helpers,constants}/index.js
}

function create_app {
	create_react_app $1
}

function main {
	if (in react app already create files) {
		add_boilerplate_files
	}
	else(create new app) {
		create_app
		add_boilerplate_files
	}
	echo 'Application finished'	
}

