#!/bin/bash

# Purpose: Fast Switch between git users

# Constants
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if [ $# -eq 0 ] ; then
  printf "${RED}No arguments supplied [ gss github home ]\n"
  exit 1;
fi

if test $1 == "gss" ; then
  git config --global user.email "andre@gosmartsolar.com" 
  printf "Switched to gss git account: ${GREEN}andre@gosmartsolar.com\n"
  exit 0;
fi

if test $1 == "github" ; then
  git config --global user.email "44297498+gomesac@users.noreply.github.com"
  printf "Switched to Gmail git account: ${GREEN}44297498+gomesac@users.noreply.github.com\n" 
  exit 0;
fi

if test $1 == "cocoon" ; then
  git config --global user.email "andre@cocoon.build"
  printf "Switched to Cocoon Git account: ${GREEN}andre@cocoon.build\n" 
  exit 0;
fi

printf "${RED}Error: options available [ gss github cocoon ]\n"
exit 1;

