#!/bin/env bash

# xrandr --prop | grep " connected"
# xrandr --prop --verbose | grep -A10 " connected" | grep "Brightness"
# night, afternoon, day
xrandr --output HDMI-0 --brightness 0.4
xrandr --output HDMI-1 --brightness 0.4
xrandr --output DP-0 --brightness 0.4
