#!/bin/sh
tmux new-session \; \
  send-keys 'htop' C-m \; \
  split-window -v -p 75 \; \
  split-window -h -p 30 \; \
  send-keys 'wd uy' C-m \; \
  select-pane -t 1 \; \
  split-window -v \; \
  send-keys 'wd c9' C-m \;
